thinkshout/mailchimp-api-php

- src/MailchimpEcommerce.php
List ID is not part of the API calls. List ID cannot be changed once a store is created.
http://developer.mailchimp.com/documentation/mailchimp/reference/ecommerce/stores/#edit-patch_ecommerce_stores_store_id
> Update Store method correction

- src/Mailchimp.php
- src/MailchimpAPIException.php
- src/MailchimpCampaigns.php
- src/MailchimpLists.php
- src/MailchimpReports.php
- src/MailchimpTemplates.php
- tests/MailchimpCampaignsTest.php
- tests/MailchimpListsTest.php
- tests/src/Client.php
- tests/src/MailchimpCampaigns.php
- tests/src/MailchimpLists.php
I refactored the entire code base with PHPStorm. This converted all arrays to the short array syntax. A few try/catch's were changed so that the } before the catch is on a new line. And there was a space here and there before a comma. I use Drupal coding standards for the refactoring. This commit resolves #7
> Refactoring entire code base to short array syntax and spacing.

- src/MailchimpEcommerce.php
Brings the eCommerce file up to the same formatting as all the other code. This was excluded in the short array PR because the eCommerce functions are not in master yet.
> Convert to short array syntax in ecommerce code.

- src/MailchimpLists.php
As I described in [this issue](https://github.com/thinkshout/mailchimp-api-php/issues/22), I'm unable to get updateSegment to work to add a subscriber to a static segment. This is true if I call the API directly, as well as if I call the Drupal mailchimp module's `mailchimp_segment_add_subscriber` method. I haven't created an issue or patch on D.O. for this, though I will if you would like me to. 
However, the functionality in this pull request does fix the issue for me and I'm able to add subscribers to a static segment. I have not yet added tests for this. Please take a look and let me know if you have questions or input. Thanks.
> Added support for segment members resource

- src/MailchimpLists.php
This adds the MailchimpLists::getSegment() method, which gets a single MailChimp list segment.
> Add support for getting a single list segment

- src/Mailchimp.php
- tests/src/Mailchimp.php
- tests/src/MailchimpAutomations.php
- tests/src/MailchimpCampaigns.php
- tests/src/MailchimpEcommerce.php
- tests/src/MailchimpLists.php
- tests/src/MailchimpReports.php
- tests/src/MailchimpTemplates.php
This change is backwards compatible. Constructing a Mailchimp object was
previously done this way:
new Mailchimp($key, $user, $timeout);
This commit introduces a more flexible approach:
new Mailchimp($key, $user, $http_options);
For backwards compatibility, $http_options can be an integer indicating
the desired request timeout.
If $http_options is an array without a 'timeout' element, the default
timeout of 10 seconds is added to the http options. Otherwise the
options are passed verbatim to the guzzle Client constructor.
Typical options a user of this library might want to pass to the http
client are debug settings, proxies, connection timeouts or ssl options.
Fixes #32.
> Allow passing arbitrary options to the http client

- composer.json
While this library uses an exact constraint, any patches or updates on Guzzle cannot be automatically installed by composer. A caret in the version constraint allows any version of Guzzle 6. https://getcomposer.org/doc/articles/versions.md#caret
> loosen guzzle version dependency.

- composer.json
The version of PHPUnit specified in the composer.json seems to be unnecessarily restrictive, is there a reason that it's pegged to 4.8.21 specifically?
> Allow recent versions of PHPUnit

- src/Mailchimp.php
Since this is also used in an drupal module, access to the function request (with the endpoint correctly set and everything) would be of great use. Also i added an optional flag to be able to get an array as a result instead of an stdClass obj.
> open request method, be able to get array as result

- src/MailchimpLists.php
- tests/MailchimpListsTest.php
Please consider adding support for removing members from list segments. New test passes (though there is a pre-existing failure with MailchimpEcommerce::addStore). Feedback welcome. Thanks!
> Add removeSegmentMember API support and test

- src/MailchimpLists.php
- tests/MailchimpListsTest.php
It would be useful to have a method to add tags to a member.
See https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/
> Added method addTagsMember() to MailchimpLists.

- src/MailchimpLists.php
- tests/MailchimpListsTest.php
This PR adds the `MailchimpLists:getMemberTags` method, which gets the tags on a list member.
https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/tags/#read-get_lists_list_id_members_subscriber_hash_tags
> Add getMemberTags method

- src/MailchimpLists.php
- tests/MailchimpListsTest.php
Adds the AddMemberEvent and getMemberEvents methods, plus unit tests.
Based on 
https://mailchimp.com/developer/marketing/api/list-member-events/add-event/
and
https://mailchimp.com/developer/marketing/api/list-member-events/list-member-events/
I think this is actually ready for review/merge, based on the prototype & testing instructions in this PR: https://github.com/thinkshout/inkling/pull/5
> Issue 3189464 integrate events

- src/Mailchimp.php
- src/MailchimpCampaigns.php
mailchimp-api-php/src/http/MailchimpCurlHttpClient.php calls http_build_query passing NULL which is an error in PHP 8.
> PHP 8 fix: $parameter parameter of request() accepts an array as default not NULL

- composer.json
Adding an open source license that matches the license for the Drupal MailChimp module based on the request in #79
> Add GPL2 or later license

- src/Mailchimp.php
- src/Mailchimp2.php
- src/MailchimpApiInterface.php
- src/MailchimpApiUser.php
- src/MailchimpAutomations.php
- src/MailchimpCampaigns.php
- src/MailchimpConnectedSites.php
- src/MailchimpEcommerce.php
- src/MailchimpLists.php
- src/MailchimpReports.php
- src/MailchimpTemplates.php
- src/MailchimpUser.php
This is a significant refactor to get this library to support access by both api_key and OAuth access_tokens.
It required creating a second Mailchimp class for initializing the connection to Mailchimp's API. Mailchimp class is used for all api_key calls. And Mailchimp2 is used for all OAuth access_token calls. 
Additionally, the structure/relationship with the Classes that were extending the Mailchimp Class had to be reworked. Those classes now are instantiated with a variable for the Mailchimp class depending on which authentication method you need. 
TODO: Update README with new documentation.
> Refactors classes to allow api_key and oauth access_tokens

- README.md
MailChimp has decided to sunset the API playground. Sadly, I could find no replacement.
https://mailchimp.com/developer/release-notes/sunsetting-the-mailchimp-api-playground/
> Remove API playground; no longer supported by MailChimp.

- src/MailchimpApiUser.php
Fix for #112 
As noted in that issue as of the v3 release of this library non-supported API calls such as this would no longer be possible: 
```
$mailchimp_api = mailchimp_get_api_object('MailchimpLists');
$mailchimp_api->request('DELETE', '/lists/{list_id}/interest-categories/{interest_category_id}/interests/{interest_id}', $tokens);
```
The change in this PR would fix the BC break introduced in the v3 release.
> Allows requests from API user objects

- src/Mailchimp.php
- src/Mailchimp2.php
- tests/MailchimpTest.php
The phpunit test for the library version is failing because the constant in the Mailchimp and Mailchimp2 classes is outdated.
This PR:
* Removes a hard-coded version check from MailchimpTest::testVersion() (only need to check against the composer version)
* Updates the VERSION constant in Mailchimp and Mailchimp2 classes
Alternatively, it looks like the VERSION constant could just be removed because it isn't used outside of the phpunit test.
> Fix version test

- tests/MailchimpAutomationsTest.php
- tests/MailchimpCampaignsTest.php
- tests/MailchimpEcommerceTest.php
- tests/MailchimpListsTest.php
- tests/MailchimpReportsTest.php
- tests/MailchimpTemplatesTest.php
- tests/MailchimpTest.php
- tests/src/Mailchimp.php
- tests/src/MailchimpApiUser.php
- tests/src/MailchimpAutomations.php
- tests/src/MailchimpCampaigns.php
- tests/src/MailchimpEcommerce.php
- tests/src/MailchimpLists.php
- tests/src/MailchimpReports.php
- tests/src/MailchimpTemplates.php
- tests/src/MailchimpTestHttpClient.php
The library was recently restructured and this broke many of the phpunit tests. This PR provides fixes.
Please also see PR #117
> Fix tests after version 3 restructuring

- tests/src/MailchimpApiUser.php
- tests/src/MailchimpAutomations.php
- tests/src/MailchimpCampaigns.php
- tests/src/MailchimpConnectedSites.php
- tests/src/MailchimpEcommerce.php
- tests/src/MailchimpLists.php
- tests/src/MailchimpReports.php
- tests/src/MailchimpTemplates.php
> Creation of dynamic properties is deprecated in PHP 8.2.

- src/Mailchimp.php
- src/Mailchimp2.php
Without it it was not possible to process the batch operations. As an alternative it could use a getter to get the information.
Fixes #119
> Make $batch_operations variable public
